# Generated by Django 5.2.15 on 2026-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.IntegerField(blank=True, choices=[(1, 'Table 1 - 2 Seats'), (2, 'Table 2 - 2 Seats'), (3, 'Table 3 - 4 Seats'), (4, 'Table 4 - 4 Seats'), (5, 'Table 5 - 6 Seats'), (6, 'Table 6 - 6 Seats'), (7, 'Table 7 - 8 Seats'), (8, 'Table 8 - 8 Seats')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'time', 'table_number')},
        ),
    ]
